Add check .start_codon_complete (#230)
Using release 69 of Ensembl, I ran into an issue where some transcripts existed which had an annotated start_codon that only spanned two positions (example ENST00000543092).

Because of this, when .complete() was run, self.coding_sequence would hit an error when it tried to determine the _codon_positions:
ValueError: Expected 3 positions for start_codon of ENST00000543092 but got 2

It seems that more recent releases of Ensembl do not have this issue (they no longer list a start_codon for these cases).

To continue using Ensembl 69, I added the additional property .start_codon_complete which catches a _codon_position ValueError and returns False, and added self.start_codon_complete as an additional check in .complete().